include ../common/config.mk

TARGET = playActivityUI
CFILES := $(CFILES) ../playActivity/playActivitySchema.c
LDFLAGS := $(LDFLAGS) -lSDL -lSDL_image -lSDL_ttf -lsqlite3

include ../common/commands.mk
include ../common/recipes.mk
